#!/usr/bin/env python3
"""Generate `samples/<lesson-id>/` from a lesson's own code blocks.

DESIGN.md 3.1 promises "runnable code per lesson, extracted and kept in sync".
Extracted is the important half: a downloadable project that was written by
hand beside the page is a second copy of the code with nothing keeping the two
in step, which is exactly the failure mode called out for `cyber-graph-demo`
(DESIGN.md, Q3). Generating the sample from the blocks means the file a reader
downloads cannot differ from the text they read, because there is only one
source.

    python3 site/sync_samples.py            # write the samples
    python3 site/sync_samples.py --check    # fail if they are out of date

`--check` runs as part of `just build`, so a lesson edit that is not synced
cannot reach the published site.

Only Rust lessons need this. Python and R snippets are pasted into a session as
the reader goes; a Rust program is not usable until every piece is assembled
into a cargo project, which is a poor thing to ask someone to do by hand from
four separate fences.
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "verify"))
from extract import extract  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
SAMPLES = ROOT / "samples"

# The dependency list the lesson shows the reader. Generating Cargo.toml from
# it means the published dependency block is compiled by the verification run,
# rather than being prose nobody checks.
DEPS_RE = re.compile(r"^```toml\n(\[dependencies\]\n.*?)```", re.M | re.S)

BANNER = (
    "// Generated from {src} by site/sync_samples.py.\n"
    "// Edit the lesson, then run `just sync-samples`. Do not edit this file:\n"
    "// `just build` fails when it does not match the lesson it came from.\n"
)


def die(msg):
    print(f"sync-samples: {msg}", file=sys.stderr)
    raise SystemExit(1)


def rust_sample(lesson):
    """Return {relative path: content} for one Rust lesson's cargo project."""
    src = CONTENT / lesson["file"]
    blocks, errors = extract(src)
    if errors:
        die("; ".join(errors))
    rust = [b for b in blocks if b.lang == "rust" and not b.skip]
    if not rust:
        die(f"{lesson['id']} is track=rust but has no runnable rust blocks")

    rel = src.relative_to(ROOT)
    main = BANNER.format(src=rel) + "\n" + "\n\n".join(b.code for b in rust) + "\n"

    mo = DEPS_RE.search(src.read_text(encoding="utf-8"))
    if not mo:
        die(f"{rel}: no ```toml block starting with [dependencies]; the sample's "
            "Cargo.toml is generated from the one the lesson shows the reader")
    deps = mo.group(1).rstrip("\n")

    cargo = (
        f"# Generated from the dependency block in {rel} by site/sync_samples.py.\n"
        f"# Edit the lesson, then run `just sync-samples`.\n"
        f'[package]\nname = "{lesson["id"]}"\nversion = "0.1.0"\nedition = "2021"\n\n'
        f"{deps}\n"
    )
    return {"Cargo.toml": cargo, "src/main.rs": main}


def sync(manifest, check):
    stale = []
    for lesson in [L for L in manifest.get("lesson", []) if L.get("track") == "rust"]:
        out = SAMPLES / lesson["id"]
        for rel, content in rust_sample(lesson).items():
            path = out / rel
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current == content:
                continue
            if check:
                stale.append(str(path.relative_to(ROOT)))
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"sync-samples: wrote {path.relative_to(ROOT)}")
    if stale:
        die("these generated files no longer match their lesson:\n    "
            + "\n    ".join(stale)
            + "\n  Run `just sync-samples` and commit the result.")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report staleness instead of rewriting")
    args = ap.parse_args()
    # Imported here rather than at module scope: build.py imports this module
    # for its own check, and a top-level import back into build would be a
    # cycle. Deferring it also means the manifest is loaded by exactly one
    # loader, so a manifest that parses for the build parses here too.
    sys.path.insert(0, str(ROOT / "site"))
    from build import load_manifest
    sync(load_manifest(), args.check)
    print("sync-samples: samples match their lessons"
          if args.check else "sync-samples: done")


if __name__ == "__main__":
    main()
