// Generated from content/run/01-fraud-elliptic.md by site/sync_samples.py.
// Edit the lesson, then run `just sync-samples`. Do not edit this file:
// `just build` fails when it does not match the lesson it came from.

use astraea_core::traits::GraphOps;
use astraea_gnn::{train_node_classification_with_rng, MessagePassingConfig, TrainingConfig,
                  TrainingData};
use astraea_graph::test_utils::InMemoryStorage;
use astraea_graph::Graph;
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use std::collections::HashMap;

const FEATURES: usize = 165;        // what the real file actually contains
const SIGNAL_FEATURES: usize = 6;   // only a few of them mean anything
const SEPARATION: f32 = 0.9;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut rng = StdRng::seed_from_u64(20260810);
    let graph = Graph::new(Box::new(InMemoryStorage::new()));

    let n = 400usize;
    let mut ids = Vec::new();
    let mut labels: HashMap<_, usize> = HashMap::new();

    for _ in 0..n {
        let illicit = rng.gen_bool(0.10);
        let centre = if illicit { SEPARATION } else { 0.0 };
        let feats: Vec<f32> = (0..FEATURES)
            .map(|f| {
                let base = rng.gen::<f32>() - 0.5;
                if f < SIGNAL_FEATURES { base + centre } else { base }
            })
            .collect();

        let id = graph.create_node(
            vec!["Tx".into()],
            serde_json::json!({ "illicit": illicit }),
            Some(feats),
        )?;

        // Only half the transactions are labelled, as in the real dataset,
        // where most are unknown.
        if rng.gen_bool(0.5) {
            labels.insert(id, if illicit { 1 } else { 0 });
        }
        ids.push((id, illicit));
    }

    // Illicit funds move among themselves more often than chance. That
    // correlation is the thing a graph model can use and a per-row model cannot.
    for k in 0..n {
        let (a, a_illicit) = ids[k];
        for _ in 0..2 {
            let (b, b_illicit) = ids[rng.gen_range(0..n)];
            if a != b && (a_illicit == b_illicit || rng.gen_bool(0.3)) {
                graph.create_edge(a, b, "SENT_TO".into(),
                                  serde_json::json!({}), 1.0, None, None)?;
            }
        }
    }

    println!("graph: {} nodes, {} labelled", n, labels.len());

    let cfg = TrainingConfig {
        layers: 2,                  // two rounds of neighbour aggregation
        learning_rate: 0.05,
        epochs: 30,
        message_passing: MessagePassingConfig::default(),
        hidden_dim: Some(32),       // Some(_) selects real backpropagation
        use_adam: true,
        early_stopping_patience: None,
        validation_split: Some(0.3),
    };

    let data = TrainingData { labels, num_classes: 2 };
    let out = train_node_classification_with_rng(&graph, &data, &cfg, &mut rng)?;

    println!("first loss {:.4}  last loss {:.4}  accuracy {:.3}",
             out.epoch_losses[0],
             out.epoch_losses[out.epoch_losses.len() - 1],
             out.accuracy);

    let n_labelled = data.labels.len() as f32;
    let n_illicit = data.labels.values().filter(|&&c| c == 1).count() as f32;
    println!("always-licit baseline accuracy: {:.3}",
             (n_labelled - n_illicit) / n_labelled);

    let (mut tp, mut fp, mut fneg) = (0.0f32, 0.0f32, 0.0f32);
    for (id, &truth) in data.labels.iter() {
        match (truth, *out.final_predictions.get(id).unwrap_or(&0)) {
            (1, 1) => tp += 1.0,
            (0, 1) => fp += 1.0,
            (1, 0) => fneg += 1.0,
            _ => {}
        }
    }
    let precision = if tp + fp > 0.0 { tp / (tp + fp) } else { 0.0 };
    let recall = if tp + fneg > 0.0 { tp / (tp + fneg) } else { 0.0 };
    println!("illicit class: precision {:.3}  recall {:.3}  (tp={} fp={} fn={})",
             precision, recall, tp as i32, fp as i32, fneg as i32);

    Ok(())
}
